name: Simon Nicklas
favicon: null
layout_spectrum: 0.5720683769322932
typography_spectrum: 0.5979085599537939
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5933486053254455
  lightness: 0.23221024102531374
  saturation: 0.30683161108754575
  rhythmicContrast: 0.6547735561616719
purpose: []
